project:
  type: website
  output-dir: docs

website:
  title: "RITM AMR Network Symposium"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Programme
      - href: speakers/speaker.qmd
        text: Speakers
  page-footer:
    left: "&copy; Copyright 2025, Antimicrobial Resistance Surveillance Reference Laboratory"

format:
  html:
    theme:
      - materia
      - brand
    css: styles.css
    toc: true

editor: visual

